# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: ""
    description: "Mahmoud AbEdelsamea Eltoum"
    twitter: "obaaa8"
  analytics:
    google_analytics: ""
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    blox: floating-theme-toggler

# # Site footer
# footer:
#   copyright:
#     notice: '© {year} Me'

# footer:
#   block: minimal
#   copyright:
#     notice: '© {year} Me. This work is licensed under {license}'
#     license:
#       enable: false
#       allow_derivatives: false
#       share_alike: false
#       allow_commercial: false
#   # For multilingual sites, show a language chooser in the footer?
#   show_translations: true

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"
